version: "3.8"
services:

  central:
    image: pianglesorg/central:latest
    build:
      context: ./central
    env_file: ./central.env
    container_name: central

  session:
    image: pianglesorg/session:latest
    build:
      context: ./session
    env_file: ./services.env
    container_name: session
    depends_on: 
      - central
    command: ["wait", "20"]
    
  crypto:
    image: pianglesorg/crypto:latest
    build:
      context: ./crypto
    env_file: ./services.env
    container_name: crypto
    depends_on: 
      - session
    command: ["wait", "30"]  
  
  config:
    image: pianglesorg/config:latest
    build:
      context: ./config
    env_file: ./services.env
    container_name: config
    depends_on: 
      - session
    command: ["wait", "30"]  

  logging:
    image: pianglesorg/logging:latest
    build:
      context: ./logging
    env_file: ./services.env
    container_name: logging
    depends_on: 
      - crypto
      - config
    command: ["wait", "30"]  

  id:
    image: pianglesorg/id:latest
    build:
      context: ./id
    env_file: ./services.env
    container_name: id
    depends_on: 
      - logging
    command: ["wait", "50"]  
  
  profile:
    image: pianglesorg/profile:latest
    build:
      context: ./profile
    env_file: ./services.env
    container_name: profile
    depends_on: 
      - id
    command: ["wait", "50"]  
 
  authentication:
    image: pianglesorg/authentication:latest
    build:
      context: ./auth
    env_file: ./services.env
    container_name: authentication
    depends_on: 
      - logging
    command: ["wait", "50"]  
 
  preferences:
    image: pianglesorg/preferences:latest
    build:
      context: ./prefs
    env_file: ./services.env
    container_name: preferences
    depends_on: 
      - logging
    command: ["wait", "50"]  
 
  msg:
    image: pianglesorg/msg:latest
    build:
      context: ./msg
    env_file: ./services.env
    container_name: msg
    depends_on: 
      - logging
    command: ["wait", "50"]  
  
